// Code generated by "esc -o client.go -prefix client/dist -private client/dist"; DO NOT EDIT.

package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// _escFS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func _escFS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// _escDir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func _escDir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// _escFSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func _escFSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// _escFSMustByte is the same as _escFSByte, but panics if name is not present.
func _escFSMustByte(useLocal bool, name string) []byte {
	b, err := _escFSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// _escFSString is the string version of _escFSByte.
func _escFSString(useLocal bool, name string) (string, error) {
	b, err := _escFSByte(useLocal, name)
	return string(b), err
}

// _escFSMustString is the string version of _escFSMustByte.
func _escFSMustString(useLocal bool, name string) string {
	return string(_escFSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/css/app.css": {
		name:    "app.css",
		local:   "client/dist/css/app.css",
		size:    162,
		modtime: 1615152862,
		compressed: `
H4sIAAAAAAAC/9JLTs0rKUpVqOblUlBQUCjPTCnJsFKwMFC1hgjkJhalZ+ZZKRgoJJaW5FvzctXycvFy
KZdkluSgazIyNSiogKsoTk0sSs4ISS0uQVNmDjYbWZFTaUlJfh6aMkMDqGmAAAAA//82pNsJogAAAA==
`,
	},

	"/index.html": {
		name:    "index.html",
		local:   "client/dist/index.html",
		size:    876,
		modtime: 1615152862,
		compressed: `
H4sIAAAAAAAC/4STX2/aMBTF3yv1O3h+rYgHGlO12XmAIsQftdVA63g0joNNHTvyvaFkn35qgta0qOLp
3pv8ztG50Q3/cvcwXm8eJ8Rg4dLrK/5aiZN+J6j2NL2+IoQQbrTMTn0zo0WnU87a2nlRaJREBY/ao6Co
j8heHX8SZWQEjaLCvHdLCeuKnPXPJGonKGDtNBitkRITdS6oAmCyLBMF8KbirBOIb0NWd+0yeyA2E7SQ
1lOinAQQVGmPUdMO945tFjmDuemnGCJ4m+c90DIqw5npp5xl9vCZVcuNg8cYHFwI0CitLyvsaNf6iO8/
0X90WyEG32FHzQOark7pWuBjtst5f2moHF6K+9HobAYVbYkEohLUIJbwgzGV+T0kyoUqy52MOlGhYHIv
j8zZLbC/usTA+skg+dr2SWF9sgdKrEe9ixZrQcHIYX/QG8XD7829WZjv9Wo9+DYZ3m3YMpTLh2F2c7vY
FLM/dSxHs/ngcXEzruv5C1PL1ZSN8nkonpbj/mzr7mNh509TF6eVXiwzNnl+EYISFQNAiHZnvaDSB18X
oQKactau9NmS+/Y89+coZ6fD5M0vkP4LAAD//zW/ovJsAwAA
`,
	},

	"/js/app.js": {
		name:    "app.js",
		local:   "client/dist/js/app.js",
		size:    2479,
		modtime: 1615152864,
		compressed: `
H4sIAAAAAAAC/6xW3XLTOBS+5ylcwbTWRFWSAoU6dZlZYH9mgO4w7VXIdFT7JHHrHJmjozQh+Fn2cu/3
yfYRduzESQsN9GLvFOnTd36+40/ZGXpMOLMYcGiUVV4u1jtJiArkIhuGO7aPg+XK1KupoYBi0UBFHPO8
ADsMCD77jGB3d7XoVXeqn5KAPWFAIaqdjqz2i2avWO3xmOxNSDHCTfCWyFIoXhtEy8EwwzSY2NTnEOyJ
FrbEnpBSJzaFWLw/fXP+7u3Fh9Ozi19Pzz+8EYpKiquU4wXMCkvsokVZqir1fmegE5PnIenVkWqKCEEu
VgklYY3tDvow+PoVZKlIbS6wWnaqXKGrSM1hObQUVt0pHtIdBXGnB8de54AjHveg1ZJJ6PswkL0mlTJc
dKP+JkmFiuRCeAeBY8oSFr3TyytIWKcwzBD+JFsA8TwkJS4uwL2vuybUYmpyD9FOp5SK9AgQyDC8y/A6
ntosDTq9Km2rOO4LnxZRu81kkmsgbQvAek3a0ijqPn36ol3J4jEBob4BJ/NLoMzozEWHR4dH3wNhZlPv
dApujolO7GQLbh0VSGcHhSabXG/jfPZCZ8X+8+7+4cv97tGRBr8FuCI80Bl/mcya6N3bwDFzE16bZISz
dWV2Er3sbK+cM5zvTwv3k5q0YzA5j7XL7qW7ubnRbIkAWYOvO/7sefcHYR+AJWjQuUE2+wisyUcHL7o/
qGdi4TrDkZ7AlmqyYvpMN+ixIZrr3N9b09Tk5to4TTbPrU7RmctlP+/PoJbeLqftW8RKniZsmsMS90O9
9RcgezlncHo2//KTCZ4eugIgfQCrv+nUfHdRg94Tba7MLFxUX30kfnt7JpSnPKpzd1G7naSor1wKeTYl
jcDt0biNI+sMjhpul2eO1z8uLsGx5hkLxdkErOfoaaejnE8ScC667WA2Bu2KPONQfMJPKGSpoLLSDajC
cPm9C9xmqawAYzExIwSOXs049oTRJWfjSLRqU7e7u51juzIuucBWLF6JXuN+FHcUx7ZHx9x4G7VaS14T
c58GveoGUyxagJWNn3/847WdFBYBOTSyJXZFiTFq5y8dU9hRuCLa766NF8tSLcqBOvif/bF2Qh9DKHR7
2QIhe09C8diBoWT8i2e2KKS2GIokz5JrcecR2SZ/+7MHmguVGjbR4nO0YTyDGQuppyYPZVmfn9V3r5zF
n0u+FGvD9hGcz9mJ+pFFDZOC56FU0FiFk3dl2hzcr5eyS8VCUwU5TrPpSfX4mqIATMNqyxUGT4TUDDMO
rUYzASmV2UD2jk0wJhjGYq/l74xdaHWGQzs2bvw7zGRrT5z8+9ff/xy3zcmelAobDiNLyB08MAfxwQbr
Ntxl+f5zqIqEe/sHt5p3K9Qy+vbg9X+XYATMGY4CWuchy1KWslSLzVxF3XJQDbHqHwxk71G7/Thw1lMC
701RZDg6//guNkWhr5yemOLRfwEAAP//XxFXA68JAAA=
`,
	},

	"/js/app.js.map": {
		name:    "app.js.map",
		local:   "client/dist/js/app.js.map",
		size:    6352,
		modtime: 1615152864,
		compressed: `
H4sIAAAAAAAC/6xY7VbbOPq/FY3+HOochA1th7ah6fxlY9IMUIYCneliDnVsJTFxJCPLEGByLftxv++V
7SXseSTbcUIZ6J7paYT86Hn5PS96vcfXTOaJ4Lj9iuBcFDJiOW6fYS5idjERcZGy3OlLcZMzuZ6F0di5
yCRLi5jZlzkmOJeRo3JnEg45U7ZaICUcCOcE83BitEpMMMMEc0ywwgQLTHCCCR5ggiNMsGRXRSKBo8AE
h5hgX0oBUpGIgZyBgmkmpLYUhWmKCU4ZH6oRJngTE2wwg34ZRmMmgW8Qpmk/jMYnc9IK6L8Mp8B4m2mL
EnSpZMJEAdjyIopYDrxxqABKnqUJDLAS0pBxJkPF9hM+Bj/4QIzCHHCkhnKRNGBcbM4/QAkHj04/9zwx
yQRn3Jjs5wpGTTi1iIBYXWCCrzDB12Fa4jkxoFdyFspo9JnlRapDwiaZugVLQkrGNekCwK+UBD9lE2Os
JEAcsozxGEhsCt+QroZDH9kUkjgJsyzhwxy3sUcpJccUWp9S6i203WrwO+QepfRXTegagrdI7S1RfU0l
E1erMBaPqsFdzWz0k8MajSHPm94yw68NhgNK6Z5h6GllQCAF2PtkyEA4JHs1jN0SPrR/LLtyPEfXbzoE
zalWsluG46iKUmw4DmukH5cF97U+ozXUg7ShJH4sBaBxpwGwgU03+43Y7jRia+w37BjIoVb4hxY1ak3r
G41zayZ7Xg2W1NVyor9PyyQMXVL4XhfAbLg9SMK162sPJi7xqCddsuVRj5Jb3d7o9nWDYtqXjVY84Gxq
2NDtmm7HDzjNaOHRvV81CN+DfO0Bko+6e0AOqPfJIz36zp245Mqnay53dRKOSY96J2X3mNJTSIE3+Ax6
fj+Cdk9X1gE5pv6mq/uH5HfqffyiWUB/j7um4oYuCcuIbbla0Z0LMe5pWIe6OAsXYu2lOtW9f0D71oXh
1NU5O/4ICfkK4C+9oQvjR4DxMyjK3bLW/cUJPNBt1KCkrs5rogVOIZGvdPdAz8vDqgy61It3jA1wsqdr
auLuVGb9N54uqkNtbW8PlB5Ct6trcG/kGkqX+srT3aFLeuRq17vcMQV3oC29cw3kr9Q3teWTxAV4Y+1h
t46/ngL+G5e7S5ncX8ok3YOM7HcN1aPU1+53MyNIGKXsCtD5P7t6/Tklh9T7krqPZt2/NBFKtIbEvS41
jV3avQOYu7TQJAaC/h+p/tibuADkt0Z6+vP0mJRkDU6632+MOM00MXBjBM55XUZ8utM1dWNmcQz0L0Cn
Y/dVie2Uel+2TA7e1CR6+tbVcdOCR11wfLSjl+mh6y8wf6X0q/GXfobaDSf646gHH19JSD3l67nPDrTc
Ljmi3bJSn4uCMOpNvd8WtPRodxNyXM0mvVAesAeB9+7cRsy9wU5DS2XqmNLjx63DGSJJGW7DXlkefMxZ
yRNcwS7aPsPWoOCRSgS3WvdVF0mLEU5UgyKshAxa98nA+omfJeemx3TvOpQo6gS44g1wpwOnEzFA5clo
dbXsbIPUYHU1akmmCslRZCXkp40W0IuKVpQ00Bt2OLtB+jhlBdgLORcKDRIeI3NiQi8CvJasBfhFgFvb
aiTFDQptOKR0AnxwuHO67198Ojy52D08/bQTYBLOQGvWAR869+WZrH0/m22DL2cb5zaczqzMLodIHR1p
HOUdzbh5fibPt0vAwuJ//ilbM5KRuaAkJoSzkgksVoOzgZAWaCueFzaSdDa2k/fKNmfG7WRtrSUsBdGv
MVR25KxltTDBjuOg95INmGQ8YigL1agTYNt2bNtZOCb/PxjNnTuWKeEkPGZTO7ZVHmDkfAhkwOHnOCgS
XIUJz1GI0iRXSAzQQDKGRMY4qo6LwBsJnquKsp/k6lSmqIMCPFIqy9uOE8XcvsxjlibX0uZMOcORw4ci
D/nQqRSBifrjos9yZaupCvB2A1F1Ps4JGsqw32cxGkgxQWrEKvMGaiHTObDlUzXqoDMYRQihABdx1nYq
wzb4pvvSFnLY3nz16o0DJVjwiAWYPCYW3faZTEI7ydtb77be/ZUIm4q4yO2Y5bc8siMxeVKixsSknbzM
bCmi8dN2Xr+xk2z95831rbfrm+/e2ax4UqQ08tJO1N1kWmHb/L4I5LYEZ4fRkE/rWIhJ++3Gc6KmEn67
fp3lz46CnSsWpmpk58kTJm5ubuzy4mCzQufy9c+bzwL1Q1KSVXJpyFW4DpdLWbRfvtl8VgQmgo0TPrQn
7En/k+z6tV3JjUIpb+20eCIK12EajsPcliJNhR3zPOyb/DyFT5ecMHPgcd6yBCpQccqMxDPrzL5jUvRv
Fcvt6e3ds+fa9VaeMRb/kKXiZkPb+B7/eb3CpKxexfI2ypVM+PBsPrxiw0Xcuq+MwCraRi+6/smL2nAh
0/bSSliPlVf2Nnq1sVETy9t7G9X7rgXX5sp8C9XmtIr5EgZctr7qWwEOAg7/cWu74p7VFvQzQFP/4zqX
V8q5NujMWnUozK4219l8YrCq+/h3fIAIpwkfow76Zt4O2r9MVaeQvN1Xyai9cl8Jz77VxpMBsmqQq6s1
4HJvRB/QxpJL2sQa7EC/lBtINTIQElkL+xVsa5XGJTVNVd+U7KzcP3wNqZC1ZqvfFizNHgDq6D+2eTyx
Noj5NE6sb7YWgw2dcn8HNj04+7s3+WSi03iPjgombz+zPBM8Z2hmdtUA2455toFaKwNZizRT3pQwaW3s
2ytWgP/P6HELpeDY07IFtwIcpUk0DjBBF6jzwYTeuP7smfbCuQLkc6rj6ImBlEB9hsI4ZjH0NVdZju2K
18yze3TVRg2MJwxOHS37OkytVmMaOY6GAeWiLdwwFEqG2DRjkUr4ECW8TNiCgRMD/TIX/MX/uBIsJKfV
jBP8M8W8+L6GOk2PSmKAW3OpRX5bv8ZZ8/ltmGDi6WWmeqRbmh+OAxEGx+HILkszj8w2o6IK32Mqa38W
nwFLh97HyfWHBT+0L4u8tnkmtLRAnoUcJGzFpsqq9nYeTlirtf1MNd/eh2gk2aAT4JX7hZWu0td4gWzN
AvzhP//817/fO+GHbw+NLMa9srFouvXYQjJDLM3ZYsR+NF7Pj1aAPwk0L55FVD/syOxHd6a/vbD/Engj
Wn8ZEn0xRUOm9JyX8+g8WL8b22WjCz98PvtvAAAA///5ykgb0BgAAA==
`,
	},

	"/": {
		name:  "/",
		local: `client/dist`,
		isDir: true,
	},

	"/css": {
		name:  "css",
		local: `client/dist/css`,
		isDir: true,
	},

	"/js": {
		name:  "js",
		local: `client/dist/js`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"client/dist": {
		_escData["/css"],
		_escData["/index.html"],
		_escData["/js"],
	},

	"client/dist/css": {
		_escData["/css/app.css"],
	},

	"client/dist/js": {
		_escData["/js/app.js"],
		_escData["/js/app.js.map"],
	},
}
