// Code generated by "esc -o client.go -prefix client/dist -private client/dist"; DO NOT EDIT.

package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// _escFS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func _escFS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// _escDir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func _escDir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// _escFSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func _escFSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// _escFSMustByte is the same as _escFSByte, but panics if name is not present.
func _escFSMustByte(useLocal bool, name string) []byte {
	b, err := _escFSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// _escFSString is the string version of _escFSByte.
func _escFSString(useLocal bool, name string) (string, error) {
	b, err := _escFSByte(useLocal, name)
	return string(b), err
}

// _escFSMustString is the string version of _escFSMustByte.
func _escFSMustString(useLocal bool, name string) string {
	return string(_escFSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/css/app.css": {
		name:    "app.css",
		local:   "client/dist/css/app.css",
		size:    162,
		modtime: 1614986342,
		compressed: `
H4sIAAAAAAAC/9JLTs0rKUpVqOblUlBQUCjPTCnJsFKwMFC1hgjkJhalZ+ZZKRgoJJaW5FvzctXycvFy
KZdkluSgazIyNSiogKsoTk0sSs4ISS0uQVNmDjYbWZFTaUlJfh6aMkMDqGmAAAAA//82pNsJogAAAA==
`,
	},

	"/index.html": {
		name:    "index.html",
		local:   "client/dist/index.html",
		size:    647,
		modtime: 1614986342,
		compressed: `
H4sIAAAAAAAC/4SSQW/iMBCF70j8h9m5sxa3ldb2YdmeW7VcejTOpDY1TuSZIPj3FQmiBlRxmkzme0/P
Hutf/59X6/eXJwiyS3Y+06cKyeUPg5TRzmcAADqQa87fYy9RElmtploNdiQOfJeFshgUOog6Of4FH1xh
EjNIu/iDoGpRivkTCiWDLMdEHIgEIRRqDXpm5fr+t2f+VmlVBdKbrjnWdk3cQ2wM7lzMCD45ZoOeshTC
irtix4PcwTosrXSFc2zbBZMrPmgVllarJu5/spq4VZeldIkfBBiVMfeDVNo1HeT6ii7oZhDpcsX+G3+g
fTunm4DbbI/zvhIPSR7FvTW669mX2Atw8Qa30+a2jFaraXDZ33lnenwd9isAAP//aLgc6YcCAAA=
`,
	},

	"/js/app.js": {
		name:    "app.js",
		local:   "client/dist/js/app.js",
		size:    1015,
		modtime: 1614986344,
		compressed: `
H4sIAAAAAAAC/4xS30v0OhB996+oubAmNMT11RouqHvhgj9A9KkUCe3Ujbc7qdPpqtT+75esrX6CH34U
SnLOZObknOzXPZbsAyYkg+61V8MHUkrWoAZfy/0+5+J9FXarraMErZhLhbX82kKoE4Kn3hMsFtMii2dg
sUBFwD1hgpL1/lJFvJ6xesJ4TeFZokV4TlZEgaQ4c4iBk9pjlWxC1TeQHIiUU3EglDJlqMCKy+vzu4vV
/dX17f0/13dX50LjiDZKtgO8tIG4Ox7GUUfp+bIwpWsaiWai9HwJCWqYBJVyV3tU5FC8vYEaNerPA6Tf
nRqn6jhpJsc6kIzu1H/ijga7zODEmwbwgdcZpKkqpc+hUNksZZTD0XH+KVKzxl9CChGZA6lC2W8A2ZQE
jmHVQNxJUfmtUJp+y3etQ6EyMh4R6BZe2LJBtwGNxrUtYHW29k0lSWn4AqAaP3o+AE8NT1//raTowFG5
Pu2ZAwplXFWttoB84TsGBJKibHz5n/jif7wG2x9aRn1CZTVwuZbi8KkHev37yYqUzdY1PSjDa0D5Ta5g
HruAUo3flMzB/Tj+Brq+4U6ojE3tqeOdFZliQ7AJW3h3hk3jJmr32MFwIALkTs2T0C412U8iwxOaXwKm
qQqSNeVYqAyaDpK4HWIox+IqJLOKUe0+PYxF/On8qFDZ3uHhX0kXeirh0rWtx4e7mwvr2tY8dmbj2r3/
AwAA///QUVVq9wMAAA==
`,
	},

	"/js/app.js.map": {
		name:    "app.js.map",
		local:   "client/dist/js/app.js.map",
		size:    3571,
		modtime: 1614986344,
		compressed: `
H4sIAAAAAAAC/4xXbVPbMBL+K6rmBuxB57TX6X1ILncjGxNSCDkuMFcGM9S1lUStIxlZDjBp/vvNSn5N
X64fEPJq99lnV2vvZoe3TBVcCjx8T3AhS5WwAg/vsZApe9zItMxYMfii5HPB1F/zOPk2eMwVy8qUeV8L
THChkoEuBpuYC08X+IFgEW8shMIEM0ywwARrTLDEBHNM8BITnGCCFXsquQKNEhMcY4JDpSRYJTIFcQ4A
L7lUGjwlcZZhgjMmVnqNCX6HCbYEwTpNFyxWyfo/rCgzbdBhU4QZ2zABAi2V6u3ao1QmZbVNFIs1a48g
mvaJC8HUDXupT8BznjORBmuepZjgFath/ddpaomFWyb0JS80E8zkZGvBCkMY0FoHS6YTCG4bZyWg6zUT
NphcigIkXwsJkjTWkLElV4WunSu2kVtWP2Vxe1JFDGl8hCt4jOGmNnGec7Eq8BAHlFKyoLCGlNKgt07q
w5+Ip5TSj0YwsYKgL50eSEMjJRvfQFiP1/XhmVG2+GTesLHidpkeKnzsKMwopRdWYWrAQEBK8HdlxSCY
k4uGxllFH9ZPh6EsWnZfugHBcmtAzqp0XNdZSq3GvGF6fmh4afAsamwOaQck/dUVAOJph2CHm1kuO7k9
7eTW+u/4sZRjA/jJmFpYu4YWsfVmby9oyJKmWm7M8219CQEPjHxhLmDlG/Z/94F+kJ8C7MyIuG+ufhGQ
hNKEzGn4EpiD5Kwrv6bBeyu/C8gtpXcmwOsZuaDBOjAPbEbuKL07JxMavvet6NqIrsiEfg1S62hGGKWM
rHwwDAj3gQPkZlHV9YSGA78lKP2brl1Cw+x0CoVj3Zm0fPNDMqeBCAIog4sGiN61lbkA98E7/6xVgaub
fiRTem4ubZb5NiOTrkPu08lLYLLLNj65o0HuC6PIpG8o5PbpySf/pZMPxu/U3PPFlCxo+G/ALvzqFQj7
7/VVo0cvu2X2wTfM/wZmQe6/+O0tntJnvyqRBZ1mvTO68qEiQvNOzcxHKWN4CF/GqkfYthJIoeErN7zH
zrIUieZSOO6u3iLlMCKI7kikw8nS3fGl80bc8we7Y2a3jRVKxhGudSM8HuvXnMklqvrK0VG1GYHV8ugo
cRXTpRIocTh589YFeVnLykoGuPFYsGdkmpET4SAWQmq05CJFtt+g4wif8JMIH0fYHem1ks8o9qBpjSM8
m5/eXoaPV/Obx7P57dVphEm8B9R8DDGMd1VHG+72+xHEcv/2wYPe5uRedUSa7CgbqBgbxXcP9+phVBGW
jvj+Xbl7kpPWUBGbwn2lBB7rw/1SKgfQyj9LG+HjtyP+D+3ZjjviJyeudDRkv+FQ+1F713ExwYMB4hvw
hnaoiF/PWZZJtEdLJTcowt5gpRjTER5FKhKDAWouuljLZ6PspHx7FW/YEBVacbEiSHSeXLSrLBFKpCg0
YplGY1T3b6/ffmswd9RYsUx7TRNH44akI7p6++p/SyvChjoXqwgTFOGb15wtEsVzDSUA6vBnOX0ptZbi
N7SiqvX7RrEGsGbe4cDgHCcZT74dE2TmBjT+p00CQna1Pn+YJf7APWhH2EVxgc5vZpdTkZe1XhMRQmYi
cT4PnkqmXv/1NP7L7gdfnplW9p9da+HB0OLUIwsQrvceDC+O29ODQaYTVB1Qf3z7g2js4FfU2QSk+v9g
gNgm169IlhrJLK3B6/PnNc8YcvouvXa0clty6ICY15m5DgGaAaxltG/zihBfIhO9V09nPT+DAYrTFHGB
4GN0wBihpVTIsamqzJFcol/DIXQwIh+wJTVMS7aiazaIZQXr4v0/tF314kb4SqLmbtD+IBeoluzbt6j5
Kvzex9BU7SH9IYrFK0FN7L0U/aSaevO+E+GUb9sS6kJ0fgj8zr7IY9ECdIx6n52KjwfnlWqfotf5WeF0
UNzOm3lQbl2LPliVYVjww/5/AQAA//+fno4Q8w0AAA==
`,
	},

	"/": {
		name:  "/",
		local: `client/dist`,
		isDir: true,
	},

	"/css": {
		name:  "css",
		local: `client/dist/css`,
		isDir: true,
	},

	"/js": {
		name:  "js",
		local: `client/dist/js`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"client/dist": {
		_escData["/css"],
		_escData["/index.html"],
		_escData["/js"],
	},

	"client/dist/css": {
		_escData["/css/app.css"],
	},

	"client/dist/js": {
		_escData["/js/app.js"],
		_escData["/js/app.js.map"],
	},
}
