// Code generated by "esc -o client.go -prefix client/dist -private client/dist"; DO NOT EDIT.

package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// _escFS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func _escFS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// _escDir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func _escDir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// _escFSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func _escFSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// _escFSMustByte is the same as _escFSByte, but panics if name is not present.
func _escFSMustByte(useLocal bool, name string) []byte {
	b, err := _escFSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// _escFSString is the string version of _escFSByte.
func _escFSString(useLocal bool, name string) (string, error) {
	b, err := _escFSByte(useLocal, name)
	return string(b), err
}

// _escFSMustString is the string version of _escFSMustByte.
func _escFSMustString(useLocal bool, name string) string {
	return string(_escFSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/index.html": {
		name:    "index.html",
		local:   "client/dist/index.html",
		size:    255,
		modtime: 1614883744,
		compressed: `
H4sIAAAAAAAC/0yOu07AMAxF90r9B+OdZEXCyQJsSDCwMIbEpKnaNEqMBH+P+gBluraudY7p5vHl4e39
9QkmWRc7DrQnLC5Hg5zRjgMAAE3swjUfuyRZ2JI+sytWFgd+y8JZDAp/i96J9+AnVxuL+ZLP2zsE/UfW
HZo+tvDT0wqkYDBWZkk5on3eXEg5glKKdOkvm6+pCLTqDc5Nu1LU3NCSPot/22Wg4yv7GwAA///kc02C
/wAAAA==
`,
	},

	"/js/app.js": {
		name:    "app.js",
		local:   "client/dist/js/app.js",
		size:    1291,
		modtime: 1614883834,
		compressed: `
H4sIAAAAAAAC/8STUW/aPhTF3/kUB/+l1hFWSvtI/3nZ2mmTSpk2eIoilCU31FWwM8ehRZTvPjkkBCib
9rY8Gd/ja5/fufSRVSqxUisorgUqAelh0wPQVTJuBKjddp/MwPtVaKLDzX1Bnym4bxUbWARgbWeGIIBd
F6QzGPpZSUO4uGiXt+8a1N1rifVgyFZGwbrH9YfeeXW+1+W/1dkno1/A3csUveDeGG04+xgrpS0yqVIs
dVrlhEuGAQwGYJfM8/xEp+TcjCd3s4f7+eNkOv80mT3eMQF7dMn26Je7x6FDcAYRvRba2HKEzfGhrYCj
Gg4jP4nznFu/UYouJk7noDf2M16fv45CivD2BvJO+1uBg65KoB2H3nsfTVNnoz3S6xSZNuAu7PzvwxZw
LIe3IPwP6eekFvbpFjQYeMi4DClqkmv99LZ8Z/Z6hPCAgYARbjw6EqwqCaU1MrGsS3/y45kS66eUSUVf
jS7I2DW3Amw+p3JcJ87ECdBVnFc0Qn/YMfEctjJef6Y81wiw0jLF8GTzDxk1fthOmhm9hBszOqG+Fdhs
I1Gvb/6x466lC7mZFAQgzvyrhSGy7ECj3BDUu1ItmIDjwabrgr4nRhaWCaQ6qZakrL8ge5+TW35Yf0m5
8nypFJkpvdZ/mj1Rrr09lM50e/cI17tq1KupCYQ3bnqurv5DqSuT0DguCqkWs28PQVwU/nPpL+PiVwAA
AP//m/MkQwsFAAA=
`,
	},

	"/js/app.js.map": {
		name:    "app.js.map",
		local:   "client/dist/js/app.js.map",
		size:    1868,
		modtime: 1614883746,
		compressed: `
H4sIAAAAAAAC/4xVYW/bNhD9K+xhSCXk5qTYN3v6QMtO4ySN0SVBO0RGqkq0w00mVYpK6rn678ORkqwE
HbAvBP34+N67k3Tew5MwldQKxr8hVLo2mahgfA9K5+Jhq/O6ENXJV6OfK2F+LdPs75OH0oiizsXorwoQ
KpOd2OpkY4SwIztAtqlUBKwQVLr1ogYQBCAoQLCAoAFBAsIaEDJAMOJbLQ0xakBIAWFujKZbmc4JLkng
e6mNc8rSogCEQqiNfQSEd4DgI1OMdHcuioIsyB8Qcvl07Xcu7QPRc53VW6EozEbYeSHox3S3yCmZUsLc
iu+WatimZSnVpoIxxJxzvOG0zjnn8Yv1fXf4E3jBOb9wwHsPxC/RxSt07lDcTp2Ed/zYHZ45stfHZZ/G
w4dl8ZpwMSB84JxfesLCiRGANflde5iAJV72Mc7a+LR+fl3KzSHd12FBtNw5kbO2HR+7LuWeseyTnr++
eOX0vGrqDvlAJP+vR0CKs0HAQTa3XA16Oxv01vsPfHzk1Al+dle9rF/nXvHg5p9e3IfF/m25db/v2oew
meJ2Hncml45By25KBcRmSq1fYsZ5xnGB387i2T9TXPB4O3V1yin5zcrYvyS+D/iJzsl4cYuf+MWpIy1y
TPn5H+9J/iZGwbk4J4/HeIF3nP953jbeHdPXKAsBY0jLsv3E/VSItbL0pYzvIVjXKrNSqyDcd1tmAoEK
7QDRgcR1uJfr4I26lyu/E273lBqWRQl03ASiyO5KodesHQJHR+1mQrfWR0dZaIStjWJZIPHNaUh43WF1
i5FuGinxzNzkCBKIU6W0ZWupcuaHA3ubwLE8TuBtAuHEPhr9zNIRTZgogQ/L2d3V/OF6eftwtry7niWA
aUOqZUQ1RPt2/Iz3TTOhWu5PVyMaREE5ao+w747xharIEd+t7s1q0gbWgfrxw4QNlni4aNC3sGlJ5Ngd
NmttAlKr/1/bUEanE/m7HfnxOJHHx6EOLHW/z9D5mCYMwn60sv4BdjM0oAk6ZpU1Um1Ctk9MohhjrL3+
xZHY2ugt+2VP3ObLxHMamqNbp7rv5VjjuQmM/B9HAo5+8H3Uz964ndmdN7KfJsm0qiwThWUR6yb66OU8
75TCNpgo7Kgf8Cx6WaonNbQcoiT+b0OqTQLIErjdleImM7K09BrBqvk3AAD//xC7T7xMBwAA
`,
	},

	"/": {
		name:  "/",
		local: `client/dist`,
		isDir: true,
	},

	"/js": {
		name:  "js",
		local: `client/dist/js`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"client/dist": {
		_escData["/index.html"],
		_escData["/js"],
	},

	"client/dist/js": {
		_escData["/js/app.js"],
		_escData["/js/app.js.map"],
	},
}
